import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata = {
  title: "Debug Mastery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const developerNames = ["Theo - t3", "Fireship", "Primeagen"];

function NavigationBar() {
  return (
    <nav className="text-md flex justify-between border-b-2 border-b-neutral-500 bg-neutral-900 p-4">
      <div className="font-semibold">Debug Mastery</div>
      <div className="flex gap-3">
        {developerNames.map((devName, index) => {
          return <p key={index}>{devName}</p>;
        })}
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <div className=" grid h-screen grid-rows-[auto,1fr]">
            <NavigationBar />
            {children}
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
